maj : backup 2023-08-26

diff --git a/.script/ext b/.script/ext
--- a/.script/ext
+++ b/.script/ext
@@ -1,26 +1,21 @@
 #!/bin/bash
 
-# ex - archive extractor
-# usage: ex <file>
-function ext () {
-    if [ -f "$1" ] ; then
-        case $1 in
-            *.tar.bz2)   tar xjf "$1"   ;;
-            *.tar.gz)    tar xzf "$1"   ;;
-            *.bz2)       bunzip2 "$1"   ;;
-            *.rar)       unrar x "$1"     ;;
-            *.gz)        gunzip "$1"    ;;
-            *.tar)       tar xf "$1"    ;;
-            *.tbz2)      tar xjf "$1"   ;;
-            *.tgz)       tar xzf "$1"   ;;
-            *.zip)       unzip "$1"     ;;
-            *.Z)         uncompress "$1";;
-            *.7z)        7z x "$1"      ;;
-            *)           echo "'$1' cannot be extracted via ex()" ;;
-        esac
-    else
-        echo "'$1' is not a valid file"
-    fi
-}
+# ext - archive extractor
+# usage: ext <file>
 
-ext "$@"
+[ ! -f "$@" ] && echo "\"$1\" is not a valid file" && exit 1
+
+case "$@" in
+    *.tar.bz2)   tar xjf "$@"   ;;
+    *.tar.gz)    tar xzf "$@"   ;;
+    *.bz2)       bunzip2 "$@"   ;;
+    *.rar)       unrar x "$@"     ;;
+    *.gz)        gunzip "$@"    ;;
+    *.tar)       tar xf "$@"    ;;
+    *.tbz2)      tar xjf "$@"   ;;
+    *.tgz)       tar xzf "$@"   ;;
+    *.zip)       unzip "$@"     ;;
+    *.Z)         uncompress "$@";;
+    *.7z)        7z x "$@"      ;;
+    *)           echo "\"$*\" cannot be extracted via ext()" ;;
+esac
