maj : backup 2024-04-18

diff --git a/.script/screen b/.script/screen
--- a/.script/screen
+++ b/.script/screen
@@ -6,6 +6,7 @@ ignoreScreen="None"
 version="v1.3"
 dependencies="rofi notify-send i3-msg xrandr awk grep seq"
 presets="screenPresetWork\nscreenPresetStartup"
+name=$(basename "$0")
 
 # info <msg>
 function info() {
@@ -27,7 +28,7 @@ function echo_err() {
 }
 
 function helpFunc() {
-    echo "Usage: $(basename "$0") [options]
+    echo "Usage: $name [options]
 
 Option:
 -h or --help                                Show this help message and exit
@@ -166,8 +167,10 @@ function screenPresetWork() {
     local screens=$(getConnectedScreen all "$ignoreScreen")
     [ -z "$screens" ] && error "Preset : No screen found" && exit 1
 
-    echo -e "$screens" | grep -Evq "eDP1|DP1|DP3" && \
-        error "Preset : Required screen \"eDP1, DP1, DP3\" not found" && exit 1
+    # echo -e "$screens" | grep -Evq "eDP1|DP1|DP3" && \
+    #     error "Preset : Required screen \"eDP1, DP1, DP3\" not found" && exit 1
+    echo -e "$screens" | grep -Evq "eDP1|DP4|DP3" && \
+        error "Preset : Required screen \"eDP1, DP4, DP3\" not found" && exit 1
 
     if [ -z "$choosePreset" ]; then
         choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
@@ -175,12 +178,14 @@ function screenPresetWork() {
 
     case $choosePreset in
         enable)
-            xrandr --output DP1 --auto --right-of eDP1
+            # xrandr --output DP1 --auto --right-of eDP1
+            xrandr --output DP4 --auto --right-of eDP1
             xrandr --output DP3 --auto --right-of DP1
             xrandr --output eDP1 --off;;
         disable)
             xrandr --output eDP1 --auto
-            xrandr --output DP1 --off
+            # xrandr --output DP1 --off
+            xrandr --output DP4 --off
             xrandr --output DP3 --off;;
         *)
             error "Preset : Unknown action" &&
