maj : backup 2024-03-13

diff --git a/.script/screen b/.script/screen
--- a/.script/screen
+++ b/.script/screen
@@ -1,13 +1,11 @@
 #!/bin/bash
 # author : lordpax
-# screen v1.2
+# screen v1.3
 
-action=0
 ignoreScreen="None"
-version="v1.2"
-param=""
+version="v1.3"
 dependencies="rofi notify-send i3-msg xrandr awk grep seq"
-presets="screenPresetWork\nscreenPresetHouse"
+presets="screenPresetWork\nscreenPresetStartup"
 
 # info <msg>
 function info() {
@@ -32,12 +30,14 @@ function helpFunc() {
     echo "Usage: $(basename "$0") [options]
 
 Option:
--h or --help ............................ Show this help message and exit
--v or --version ......................... Show version
--c or --connect ......................... Connect a screen
--d or --disconnect ...................... Disconnect a screen
--s or --status .......................... Show the status of the screen
---connected <primary|secondary|all> ..... Get the connected screen"
+-h or --help                                Show this help message and exit
+-v or --version                             Show version
+-c or --connect                             Connect a screen
+-d or --disconnect                          Disconnect a screen
+-s or --status                              Show the status of the screen
+-l or --list                                List all preset
+-p or --preset <preset> [enable|disable]    Load a preset
+--connected <primary|secondary|all>         Get the connected screen"
 }
 
 function checkDependencies() {
@@ -123,13 +123,11 @@ function connectScreen() {
     [ -z "$rotation" ] && exit 1
     [ "$rotation" != "none" ] && commande="$commande --rotate $rotation"
 
-    if $commande; then
-        sleep 1
-        info "Screen connected" 
-        i3-msg "restart"
-    else
-        error "Screen not connected"
-    fi
+    ! $commande && error "Screen not connected" && exit 1
+
+    sleep 1
+    info "Screen connected" 
+    i3-msg "restart"
 }
 
 function disconnectScreen() {
@@ -139,24 +137,41 @@ function disconnectScreen() {
     local screen=$(echo "$screens" | rofi -dmenu -p "Disconnect a screen")
     [ -z "$screen" ] && exit 1
 
-    if xrandr --output "$screen" --off; then
-        sleep 1
-        info "Screen disconnected"
-        i3-msg "restart"
-    else
-        error "Screen not disconnected"
-    fi
+    ! xrandr --output "$screen" --off && \
+        error "Screen not disconnected" && exit 1
+
+    sleep 1
+    info "Screen disconnected"
+    i3-msg "restart"
+}
+
+# loadPreset <preset> [enable|disable]
+function loadPreset() {
+    local preset="$1"
+    [ -z "$preset" ] && exit 1
+
+    ! echo -e "$presets" | grep -q "$preset" && \
+        error "Preset not found" && exit 1
+
+    $preset "$2" # execute the preset
+    sleep 1
+    info "Preset applied"
+    i3-msg "restart"
 }
 
 # preset for work on laptop with 2 screens
+# screenPresetWork [enable|disable]
 function screenPresetWork() {
+    local choosePreset="$1"
     local screens=$(getConnectedScreen all "$ignoreScreen")
     [ -z "$screens" ] && error "Preset : No screen found" && exit 1
 
     echo -e "$screens" | grep -Evq "eDP1|DP1|DP3" && \
         error "Preset : Required screen \"eDP1, DP1, DP3\" not found" && exit 1
 
-    local choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
+    if [ -z "$choosePreset" ]; then
+        choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
+    fi
 
     case $choosePreset in
         enable)
@@ -167,28 +182,45 @@ function screenPresetWork() {
             xrandr --output eDP1 --auto
             xrandr --output DP1 --off
             xrandr --output DP3 --off;;
+        *)
+            error "Preset : Unknown action" &&
+            exit 1;;
     esac
 }
 
-# preset for house on laptop with 2 screens
-function screenPresetHouse() {
+# preset for main pc startup
+# screenPresetStartup [enable|disable]
+function screenPresetStartup() {
+    local choosePreset="$1"
     local screens=$(getConnectedScreen all "$ignoreScreen")
     [ -z "$screens" ] && error "Preset : No screen found" && exit 1
 
-    echo -e "$screens" | grep -Evq "eDP1|DP3" && \
+    echo -e "$screens" | grep -Evq "DP-3|HDMI-1" && \
         error "Preset : Required screen \"eDP1, DP3\" not found" && exit 1
 
-    local choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
+    if [ -z "$choosePreset" ]; then
+        choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
+    fi
 
     case $choosePreset in
         enable)
-            xrandr --output DP3 --auto --right-of eDP1;;
+            xrandr --output DP-3 --mode 1920x1080 --primary
+            xrandr --output HDMI-1 --mode 1366x768 --right-of DP-3;;
         disable)
-            xrandr --output DP3 --off;;
+            xrandr --output DP-3 --auto
+            xrandr --output HDMI-1 --off;;
+        *)
+            error "Preset : Unknown action" &&
+            exit 1;;
     esac
 }
 
 function main() {
+    local action=0
+    local param=""
+    local presetName=""
+    local enablePreset=""
+
     if [ $# -ge 1 ]; then
         for _ in $(seq 1 $#); do
             case $1 in
@@ -208,6 +240,14 @@ function main() {
                     action=4
                     param="$2"
                     shift;;
+                -l | --list)
+                    echo -e "$presets"
+                    exit 0;;
+                -p | --preset)
+                    action=5
+                    presetName="$2"
+                    enablePreset="$3"
+                    shift 2;;
                 "");;
                 *)
                     echo_err "Unknown parameter $1"
@@ -226,6 +266,8 @@ function main() {
             xrandr --listmonitors;;
         4)
             getConnectedScreen "$param" "$ignoreScreen";;
+        5)
+            loadPreset "$presetName" "$enablePreset";;
         *)
             helpFunc
             exit 1;;
