maj : backup 2024-05-02

diff --git a/.script/screen b/.script/screen
--- a/.script/screen
+++ b/.script/screen
@@ -167,8 +167,6 @@ function screenPresetWork() {
     local screens=$(getConnectedScreen all "$ignoreScreen")
     [ -z "$screens" ] && error "Preset : No screen found" && exit 1
 
-    # echo -e "$screens" | grep -Evq "eDP1|DP1|DP3" && \
-    #     error "Preset : Required screen \"eDP1, DP1, DP3\" not found" && exit 1
     echo -e "$screens" | grep -Evq "eDP1|DP4|DP3" && \
         error "Preset : Required screen \"eDP1, DP4, DP3\" not found" && exit 1
 
@@ -178,13 +176,11 @@ function screenPresetWork() {
 
     case $choosePreset in
         enable)
-            # xrandr --output DP1 --auto --right-of eDP1
             xrandr --output DP4 --auto --right-of eDP1
-            xrandr --output DP3 --auto --right-of DP1
+            xrandr --output DP3 --auto --right-of DP4 --scale 1.3125
             xrandr --output eDP1 --off;;
         disable)
             xrandr --output eDP1 --auto
-            # xrandr --output DP1 --off
             xrandr --output DP4 --off
             xrandr --output DP3 --off;;
         *)
@@ -201,7 +197,7 @@ function screenPresetStartup() {
     [ -z "$screens" ] && error "Preset : No screen found" && exit 1
 
     echo -e "$screens" | grep -Evq "DP-3|HDMI-1" && \
-        error "Preset : Required screen \"eDP1, DP3\" not found" && exit 1
+        error "Preset : Required screen \"DP-3, HDMI-1\" not found" && exit 1
 
     if [ -z "$choosePreset" ]; then
         choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
