maj : backup 2023-09-26

diff --git a/.script/screen b/.script/screen
--- a/.script/screen
+++ b/.script/screen
@@ -1,16 +1,20 @@
 #!/bin/bash
+# author : lordpax
+# screen v1.1
 
-mode=0
+action=0
+ignoreScreen="eDP-1|None"
+version="v1.0"
 
 # info <msg>
 function info() {
-    [ "$1" == "" ] && exit 1
+    [ -z "$1" ] && exit 1
     notify-send "Info" "$1"
 }
 
 # error <msg>
 function error() {
-    [ "$1" == "" ] && exit 1
+    [ -z "$1" ] && exit 1
     notify-send "Error" "$1"
 }
 
@@ -25,26 +29,35 @@ function helpFunc() {
 
 Option:
 -h or --help .................... Show this help message and exit
+-v or --version ................. Show version
 -c or --connect ................. Connect a screen
 -d or --disconnect .............. Disconnect a screen
 -s or --status .................. Show the status of the screen"
 }
 
 function verification() {
-    [ -z "$(which rofi 2> /dev/null)" ] && echo_err "\"rofi\" is required" && exit 1
-    [ -z "$(which notify-send 2> /dev/null)" ] && echo_err "\"notify-send\" is required" && exit 1
+    [ -z "$(which rofi 2> /dev/null)" ] && error "\"rofi\" is required" && exit 1
+    [ -z "$(which notify-send 2> /dev/null)" ] && error "\"notify-send\" is required" && exit 1
 }
 
+# getConnectedScreen [ignore]
 function getConnectedScreen() {
-    xrandr | grep " connected" | awk '{print $1}'
+    local scr=$(
+        xrandr | \
+            grep " connected" | \
+            awk '{print $1}'
+    )
+
+    [ "$1" != "" ] && echo "$scr" | grep -vE "$1" || echo "$scr"
 }
 
+# getScreenMode <screen>
 function getScreenMode() {
     [ "$1" == "" ] && exit 1
-    xrandr \
-        | awk -v monitor="^HDMI-1 connected" '/connected/ {p = 0} $0 ~ monitor {p = 1} p' \
-        | grep -v " connected" \
-        | grep -oP '\d+x\d+'
+    xrandr | \
+        awk -v monitor="^$1 connected" '/connected/ {p = 0} $0 ~ monitor {p = 1} p' | \
+        grep -v " connected" | \
+        grep -oP '\d+x\d+'
 }
 
 function connectScreen() {
@@ -52,7 +65,7 @@ function connectScreen() {
     local rotationList="none\nnormal\nleft\nright\ninverted"
     local commande="xrandr"
 
-    local screens=$(getConnectedScreen)
+    local screens=$(getConnectedScreen "$ignoreScreen")
     [ "$screens" == "" ] && error "No screen found" && exit 1
 
     local screen=$(echo "$screens" | rofi -dmenu -p "Connect a screen")
@@ -63,12 +76,12 @@ function connectScreen() {
     local modeList=$(getScreenMode "$screen")
     local mode=$(echo -e "auto\n$modeList" | rofi -dmenu -p "Choose mode")
     [ "$mode" == "" ] && exit 1
-    local commande=$([ "$mode" != "auto" ] && echo "$commande --mode $mode" || echo "$commande --auto")
+    commande=$([ "$mode" != "auto" ] && echo "$commande --mode $mode" || echo "$commande --auto")
 
     local side=$(echo -e "$sideList"| rofi -dmenu -p "Choose side")
     [ "$side" == "" ] && exit 1
     if [ "$side" != "none" ]; then
-        local otherScreens=$(echo "$screens" | grep -v "$screen")
+        local otherScreens=$(getConnectedScreen "^$screen$")
         [ "$otherScreens" == "" ] && exit 1
 
         local otherScreen=$(echo "$otherScreens" | rofi -dmenu -p "Screen side")
@@ -81,7 +94,6 @@ function connectScreen() {
     [ "$rotation" == "" ] && exit 1
     [ "$rotation" != "none" ] && commande="$commande --rotate $rotation"
 
-    # echo "$commande"
     if $commande; then
         info "Screen connected" 
     else
@@ -90,13 +102,12 @@ function connectScreen() {
 }
 
 function disconnectScreen() {
-    local screens=$(getConnectedScreen)
+    local screens=$(getConnectedScreen "$ignoreScreen")
     [ "$screens" == "" ] && error "No screen found" && exit 1
 
     local screen=$(echo "$screens" | rofi -dmenu -p "Disconnect a screen")
     [ "$screen" == "" ] && exit 1
 
-    # echo "xrandr --output $screen --off"
     if xrandr --output "$screen" --off; then
         info "Screen disconnected"
     else
@@ -104,20 +115,21 @@ function disconnectScreen() {
     fi
 }
 
-verification
-
 if [ $# -ge 1 ]; then
     for i in $(seq 1 $#); do
         case $1 in
             -h | --help)
                 helpFunc
                 exit 0;;
+            -v | --version)
+                echo "$version"
+                exit 0;;
             -c | --connect)
-                mode=1;;
+                action=1;;
             -d | --disconnect)
-                mode=2;;
+                action=2;;
             -s | --status)
-                mode=3;;
+                action=3;;
             "");;
             *)
                 echo_err "Unknown parameter $1"
@@ -127,13 +139,15 @@ if [ $# -ge 1 ]; then
     done
 fi
 
-case $mode in
+verification
+
+case $action in
     1)
         connectScreen;;
     2)
         disconnectScreen;;
     3)
-        getConnectedScreen;;
+        xrandr --listmonitors;;
     *)
         helpFunc
         exit 1;;
