maj : backup 2024-03-10

diff --git a/.script/screen b/.script/screen
--- a/.script/screen
+++ b/.script/screen
@@ -7,6 +7,7 @@ ignoreScreen="None"
 version="v1.2"
 param=""
 dependencies="rofi notify-send i3-msg xrandr awk grep seq"
+presets="screenPresetWork\nscreenPresetHouse"
 
 # info <msg>
 function info() {
@@ -18,6 +19,7 @@ function info() {
 function error() {
     [ -z "$1" ] && exit 1
     notify-send "Error" "$1"
+    echo_err "$1"
 }
 
 # echo_err <msg>
@@ -86,14 +88,23 @@ function connectScreen() {
     local screens=$(getConnectedScreen all "$ignoreScreen")
     [ -z "$screens" ] && error "No screen found" && exit 1
 
-    local screen=$(echo "$screens" | rofi -dmenu -p "Connect a screen")
+    local screen=$(echo -e "$screens\n$presets" | rofi -dmenu -p "Connect a screen")
     [ -z "$screen" ] && exit 1
+
+    if echo -e "$presets" | grep -q "$screen"; then
+        $screen
+        sleep 1
+        info "Preset applied"
+        i3-msg "restart"
+        exit 0
+    fi
 
     commande="$commande --output $screen"
 
     local modeList=$(getScreenMode "$screen")
     local mode=$(echo -e "auto\n$modeList" | rofi -dmenu -p "Choose mode")
     [ -z "$mode" ] && exit 1
+
     commande=$([ "$mode" != "auto" ] && echo "$commande --mode $mode" || echo "$commande --auto")
 
     local side=$(echo -e "$sideList"| rofi -dmenu -p "Choose side")
@@ -137,46 +148,89 @@ function disconnectScreen() {
     fi
 }
 
-if [ $# -ge 1 ]; then
-    for _ in $(seq 1 $#); do
-        case $1 in
-            -h | --help)
-                helpFunc
-                exit 0;;
-            -v | --version)
-                echo "$version"
-                exit 0;;
-            -c | --connect)
-                action=1;;
-            -d | --disconnect)
-                action=2;;
-            -s | --status)
-                action=3;;
-            --connected)
-                action=4
-                param="$2"
-                shift;;
-            "");;
-            *)
-                echo_err "Unknown parameter $1"
-                exit 1;;
-        esac
-        shift
-    done
-fi
+# preset for work on laptop with 2 screens
+function screenPresetWork() {
+    local screens=$(getConnectedScreen all "$ignoreScreen")
+    [ -z "$screens" ] && error "Preset : No screen found" && exit 1
+
+    echo -e "$screens" | grep -Evq "eDP1|DP1|DP3" && \
+        error "Preset : Required screen \"eDP1, DP1, DP3\" not found" && exit 1
+
+    local choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
+
+    case $choosePreset in
+        enable)
+            xrandr --output DP1 --auto --right-of eDP1
+            xrandr --output DP3 --auto --right-of DP1
+            xrandr --output eDP1 --off;;
+        disable)
+            xrandr --output eDP1 --auto
+            xrandr --output DP1 --off
+            xrandr --output DP3 --off;;
+    esac
+}
+
+# preset for house on laptop with 2 screens
+function screenPresetHouse() {
+    local screens=$(getConnectedScreen all "$ignoreScreen")
+    [ -z "$screens" ] && error "Preset : No screen found" && exit 1
+
+    echo -e "$screens" | grep -Evq "eDP1|DP3" && \
+        error "Preset : Required screen \"eDP1, DP3\" not found" && exit 1
+
+    local choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
+
+    case $choosePreset in
+        enable)
+            xrandr --output DP3 --auto --right-of eDP1;;
+        disable)
+            xrandr --output DP3 --off;;
+    esac
+}
+
+function main() {
+    if [ $# -ge 1 ]; then
+        for _ in $(seq 1 $#); do
+            case $1 in
+                -h | --help)
+                    helpFunc
+                    exit 0;;
+                -v | --version)
+                    echo "$version"
+                    exit 0;;
+                -c | --connect)
+                    action=1;;
+                -d | --disconnect)
+                    action=2;;
+                -s | --status)
+                    action=3;;
+                --connected)
+                    action=4
+                    param="$2"
+                    shift;;
+                "");;
+                *)
+                    echo_err "Unknown parameter $1"
+                    exit 1;;
+            esac
+            shift
+        done
+    fi
+
+    case $action in
+        1)
+            connectScreen;;
+        2)
+            disconnectScreen;;
+        3)
+            xrandr --listmonitors;;
+        4)
+            getConnectedScreen "$param" "$ignoreScreen";;
+        *)
+            helpFunc
+            exit 1;;
+    esac
+}
 
 checkDependencies
-
-case $action in
-    1)
-        connectScreen;;
-    2)
-        disconnectScreen;;
-    3)
-        xrandr --listmonitors;;
-    4)
-        getConnectedScreen "$param" "$ignoreScreen";;
-    *)
-        helpFunc
-        exit 1;;
-esac
+main "$@"
