maj : backup 2022-05-27

diff --git a/polybar/script/brightness b/polybar/script/brightness
--- a/polybar/script/brightness
+++ b/polybar/script/brightness
@@ -3,7 +3,14 @@
 # brightness v1.0
 
 screen="eDP-1"
-version="v1.0"
+version="v1.1"
+action=0
+param=""
+
+function echoErr() {
+    [ "$1" == "" ] && exit 1
+    echo -e "\e[31mERROR :\e[0m $1" > /dev/stderr
+}
 
 function helpFunc() {
     #function_body
@@ -12,12 +19,17 @@ function helpFunc() {
 Option :
 -h or --help ...................................... Show help
 -v or --version ................................... Show version
+--screen <screen> ................................. Change screen
 -i <num> .......................................... Increment brightness
 -d <num> .......................................... Decrement brightness
 -s <num> .......................................... Set brightness
 -g ................................................ Get brightness
 -G ................................................ Get brightness as a percentage"
     exit 0
+}
+
+function verification() {
+    [ "$screen" == "" ] && echoErr "Screen must be indicated" && exit 1
 }
 
 # getBrightness [%]
@@ -28,13 +40,13 @@ function getBrightness() {
 
 # setBrightness <num>
 function setBrightness() {
-    [ "$1" == "" ] && echo "Parameter is needed" && exit 1
+    [ "$1" == "" ] && echoErr "Parameter is needed" && exit 1
     xrandr --output $screen --brightness $1
 }
 
 # brightness <+|-> <num>
 function brightness() {
-    ([ "$1" == "" ] && [ "$2" == "" ]) && echo "Parameter is needed" && exit 1
+    ([ "$1" == "" ] || [ "$2" == "" ]) && echoErr "Parameter is needed" && exit 1
 
     local brightness=$(getBrightness)
     local new=$(echo "$brightness $1 $2" | bc)
@@ -47,26 +59,48 @@ if [ $# -ge 1 ]; then
             -h | --help)
                 helpFunc;;
             -v | --version)
-                echo $version;;
+                echo $version
+                exit 0;;
+            --screen)
+                screen="$2"
+                shift;;
             -i)
-                brightness + $2
+                action=1
+                param="+ $2"
                 shift;;
             -d)
-                brightness - $2
+                action=1
+                param="- $2"
                 shift;;
             -s)
-                setBrightness $2
+                action=2
+                param="$2"
                 shift;;
             -g)
-                getBrightness;;
+                action=3;;
             -G)
-                getBrightness %;;
+                action=3
+                param="%";;
             "")
                 ;;
             *)
-                echo $"Unknown parameter \"$1\""
+                echoErr $"Unknown parameter \"$1\""
                 exit 1
         esac
         shift
     done
 fi
+
+verification
+
+case $action in
+    1)
+        brightness $param;;
+    2)
+        setBrightness $param;;
+    3)
+        getBrightness $param;;
+    *)
+        echoErr "Something wrong, type : $0 --help"
+        exit 1
+esac
